sudo: false

language: node_js

node_js:
  - '6.10'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install --ignore-scripts
  - npm run build

cache:
  directories:
    - node_modules

script:
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run docs && node create-live-demo.js; fi'
 - npm run test

after_success:
 - npm run report-coverage
