sudo: false

language: node_js

node_js:
  - '6.10'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules

script:
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run live-demo; fi'
 - npm run test

after_success:
 - npm run report-coverage
