sudo: false

language: node_js

node_js:
  - '6.10'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install --ignore-scripts

cache:
  directories:
    - node_modules

script:
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then node create-live-demo --userpassword $GITUSRPWD --currentbranch $TRAVIS_PULL_REQUEST_BRANCH; fi'
 - npm run test

after_success:
 - npm run report-coverage
