sudo: false

language: node_js

node_js:
  - '8.9'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - ls node_modules/phantomjs-prebuilt/lib/ # remove when done testing this is to test https://github.com/karma-runner/karma-phantomjs-launcher/issues/120#issuecomment-305236999
  - npm install -g gulp
  - npm install
  - npm run build

cache:
  directories:
    - node_modules

script:
 - npm run test
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "Your live demo url, if everything went well, should be https://coveo.github.io/react-vapor/$TRAVIS_PULL_REQUEST_BRANCH/"; fi' # run this line on pull request builds only

after_success:
 - npm run report-coverage

after_script:
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run docs && node create-live-demo.js; fi' # run this line on pull request builds only
