sudo: false

language: node_js

node_js:
  - '6.10'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules

script:
 - npm run test

after_success:
 - npm run report-coverage
 - node create-live-demo.js

after_failure:
 - node create-live-demo.js
