sudo: false

language: node_js

node_js:
  - '5.11'

branches:
  only:
    - master

install:
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules

script:
 - npm run test

after_success:
 - npm run report-coverage
